services:
# sevice gérant le serveur
  server:
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    working_dir: /app
    tty: true
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
    volumes:
      - ./code/server/mysql:/app
      - ./mysql-db:/var/lib/mysql
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always