services:
# sevice gérant le serveur
  server:
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    working_dir: /app
    tty: true
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
    volumes:
      - ./code/server/mysql:/app
      - ./mysql-db:/var/lib/mysql
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
# service gérant le serveur MongoDB
  mongodb:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - ./code/server/mongodb:/app
      - ./mongodb-db:/data/db
    working_dir: /app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
  client:
    image: node
    ports:
      - 5500:5500
    volumes:
      - ./code/client:/app
    working_dir: /app
    tty: true  